export const host="https://findout-backend.onrender.com";
export const registerRoute = `${host}/api/auth/register`
export const loginRoute = `${host}/api/auth/login`
export const studentRoute = `${host}/api/sro/registers`
export const campusRoute = `${host}/api/camp/registers`
export const compRoute = `${host}/api/comp/registers`
export const gradRoute = `${host}/api/grad/registers`
export const jobRoute = `${host}/api/comp/jobs`
export const CgetdetailsRoute = `${host}/api/comp/getdetails/`;
export const CoupdateRoute = `${host}/api/company/update/`;
export const SupdateRoute = `${host}/api/sro/update/`;
export const SgetdetailsRoute= `${host}/api/sro/getdetails/`;
export const gUpdateRoute = `${host}/api/grad/update/`;
export const gDetailsRoute= `${host}/api/grad/getdetails/`;
export const caUpdateRoute = `${host}/api/camp/update/`;
export const caDetailsRoute= `${host}/api/camp/getdetails/`;
export const JobLoadRoute=  `${host}/api/sro/jobs/`;
export const ApplyJobRoute = `${host}/api/sro/apply/`;
export const GradJobLoadRoute = `${host}/api/grad/jobs/`;
export const  GradApplyJobRoute = `${host}/api/grad/apply/`;
export const  CJobLoadRoute = `${host}/api/camp/jobs/`;
export const  CApplyJobRoute = `${host}/api/camp/apply/`;
export const  OnCampusRoute = `${host}/api/comp/oncamp/`;
